# Generated by Django 3.1.7 on 2021-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('disc', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=None)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
